spring:
  application:
    name: wvp
  profiles:
    active: docker

video-receive:
  enabled: true
  url: https://server-test.hoomi.cn/warehouse/sortingTask/weighingStation/video/receive
  analysis: true